export const challengeGameAbi = [
  {
    type: "function",
    name: "submitGuess",
    stateMutability: "payable",
    inputs: [
      { name: "gameId", type: "uint256" },
      {
        name: "encryptedGuess",
        type: "tuple",
        components: [
          { name: "ctHash", type: "uint256" },
          { name: "securityZone", type: "uint8" },
          { name: "utype", type: "uint8" },
          { name: "signature", type: "bytes" },
        ],
      },
    ],
    outputs: [{ name: "guessId", type: "uint256" }],
  },
  {
    type: "function",
    name: "finalizeGuess",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "guessId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getGame",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      {
        name: "game",
        type: "tuple",
        components: [
          { name: "creator", type: "address" },
          { name: "creatorStakeEscrowed", type: "uint256" },
          { name: "playerStakeFixed", type: "uint256" },
          { name: "slashBps", type: "uint16" },
          { name: "creatorCutBps", type: "uint16" },
          { name: "protocolCutBps", type: "uint16" },
          { name: "payoutBpsOfCreatorStake", type: "uint16" },
          { name: "seqLen", type: "uint8" },
          { name: "secretHandle", type: "bytes32" },
          { name: "deadline", type: "uint64" },
          { name: "active", type: "bool" },
          { name: "solved", type: "bool" },
          { name: "totalPlayerStaked", type: "uint256" },
          { name: "protocolFeesAccrued", type: "uint256" },
          { name: "attemptCount", type: "uint256" },
          { name: "maxAttemptsPerAddress", type: "uint32" },
          { name: "cooldownSeconds", type: "uint64" },
          { name: "unresolvedGuesses", type: "uint256" },
          { name: "hasGuesses", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "GuessSubmitted",
    inputs: [
      { indexed: true, name: "gameId", type: "uint256" },
      { indexed: true, name: "guessId", type: "uint256" },
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "stake", type: "uint256" },
      { indexed: false, name: "exactMatchesDecryptId", type: "uint256" },
      { indexed: false, name: "partialMatchesDecryptId", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GuessResolved",
    inputs: [
      { indexed: true, name: "gameId", type: "uint256" },
      { indexed: true, name: "guessId", type: "uint256" },
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "won", type: "bool" },
      { indexed: false, name: "exactMatches", type: "uint8" },
      { indexed: false, name: "partialMatches", type: "uint8" },
      { indexed: false, name: "payout", type: "uint256" },
      { indexed: false, name: "slash", type: "uint256" },
      { indexed: false, name: "protocolFee", type: "uint256" },
      { indexed: false, name: "playerRefund", type: "uint256" },
      { indexed: false, name: "resolvedAfterGameSolved", type: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameSolved",
    inputs: [
      { indexed: true, name: "gameId", type: "uint256" },
      { indexed: true, name: "winner", type: "address" },
      { indexed: false, name: "payout", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameExpired",
    inputs: [
      { indexed: true, name: "gameId", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "GameCancelled",
    inputs: [
      { indexed: true, name: "gameId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
    ],
    anonymous: false,
  },
  {
    type: "function",
    name: "gameCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
